<script lang="ts">
  import type { UIModelField } from "$lib/editor/form/utils/model.js";
  import Tooltip from "$lib/ui/Tooltip.svelte";
  import CalculatedIcon from "$lib/ui/icons/CalculatedIcon.svelte";
  import { Hashtag, Icon } from "svelte-hero-icons";
  export let field: UIModelField<unknown>;

  $: arrayTitle = field.schema.title || "";
</script>

<span class="text-grey-4 font-medium whitespace-nowrap flex items-center py-1.5" class:capitalize={!field.schema.title}>
  {#if field.parent?.isArray()}
    <Icon src={Hashtag} class="h-3 text-grey-5 mr-1" /> {arrayTitle} {Number(field.key) + 1}
  {:else}
    <span class:text-blue-500={field.is.calculated}>{field.schema.title || field.key}</span>
    {#if field.is.calculated}
      <span class="ml-2 text-blue-500">
        <Tooltip
          label="This is a calculated field. It will be generated by the builder if missing."
          bgClass="bg-blue-300"
          delay={1000}
        >
          <CalculatedIcon />
        </Tooltip>
      </span>
    {/if}
  {/if}
</span>
